backend:
  name: git-gateway
  branch: decap # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

display_url: https://ibrahimshuaib.netlify.app
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Bio"
      name: "bio"
      extension: json
      format: json
      file: "src/Data/bio.json"
      slug: "bio"
      fields:
        - { name: "bioHead", label: "Bio Heading", widget: "string" }
        - name: "bioBody"
          label: "Bio Paragraphs"
          widget: "list"
          fields:
            - { name: "paragraph", label: "Paragraph", widget: "text" }
