backend:
  name: github
  branch: decap # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

display_url: https://ibrahimshuaib.netlify.app

collections:
  - name: "bio" # Used in routes, e.g., /admin/collections/bio
    label: "Bio" # Used in the UI
    # folder: "_posts/bio" # The path to the folder where the documents are stored
    extension: json
    format: json
    file: "src/data/bio.json"
    create: false # Allow users to create new documents in this collection
    slug: "bio" # Filename template
    fields:
      - { name: "bioHead", label: "Bio Heading", widget: "string" }
      - name: "bioBody"
        label: "Bio Paragraphs"
        widget: "list"
        fields:
          - { name: "paragraph", label: "Paragraph", widget: "text" }
